### ISSUE TITLE
A / B group data confusion (possibly due to CDN)

### ISSUE THREAD

**Issue by guoliu** [thematters/matters-server#1598]
https://mattersnews.slack.com/archives/GA0R09FHN/p1603549134000100

Some thoughts:
Sounds the error happens during SSR. So API server could be caching correctly, and CDN is not.

**Comment by Carolusian** [comment]
# A/B Group Testing Issues Summary

# Current implementation
## Backend

In `src/common/utils/cookie.ts`, the `__user_group` cookie will be set or cleared when the user is login or logout his account.

In `src/common/utils/getViewer.ts`, whenever `x-user-group` is set in the request header or the `__user_group` value is set in the cookie. The viewer’s `group` property will be set accordingly.  This property is used in `src/types/directives/privateCache` in determining how the content to be cached. If the `group` property exists, then the cache scope with be private.

See: https://github.com/thematters/matters-server/pull/1553/files

## Frontend

New `src/common/utils/cookie.ts` file to read cookie for different key names, mainly `__token` and `__user_group`. It is used by `src/common/utils/withApollo.ts` to attach `x-access-token` and `x-user-group` to request headers in the form of Apollo links.

See: https://github.com/thematters/matters-web/pull/1587

# Issues
## Issue 1: SSR fails - resolved

Observation: when loading the homepage, the hottest feed was loaded in a separate CSR request. The intended behavior is the hottest feed load together with the SSR request.

For the fix, see: https://github.com/thematters/matters-web/pull/1620/files

## Issue 2: Displaying A Group content for B Group users in iOS PWA mode - resolved

A website works in PWA mode after using Safari’s “Add to Home Screen” function on an iOS device.

Observation: Open matters website in PWA mode, then login as a B Group user, the hottest feed is B group’s feed. However, put the PWA app in background, and kill it. Re-open the PWA app, the hottest’s feed will become A group’s feed.

Reason: It turns out the `__user_group`  cookie  is placed at the last in the cookie string without a `;` appending to the end.

![](https://paper-attachments.dropbox.com/s_5D219375E3B06386CBFAB8D7BF7F71DC7EDEB3100EC05D5425BB835F7466ADC7_1605617376023_image.png)


And, the old regular express `${name}=([^;]*);` in  `src/common/utills/cookie.ts` can not correctly parse the last cookie value. Therefore, the `__user_group` cookie was lost in the requests, because it cannot be read from `document.cookie`.

This issue is fixed in: https://github.com/thematters/matters-web/pull/1621/files

## Issue 3: Displaying A Group content for B Group users in iOS browsers - resolved

Observation: The behave is the same to `Issue 2` except that the website is opened in normal Safari or Chrome browsers on iOS devices.

Reason: But the underlying reason is diferent. iOS browsers will automatically delete `SameSite: strict` cookies everytime the browser is killed and re-opened.

Fixd in: https://github.com/thematters/matters-server/pull/1597/files

Reference:

- https://stackoverflow.com/questions/55937018/previously-set-samesite-strict-cookie-not-available-in-document-cookie-firefo
- https://bugzilla.mozilla.org/show_bug.cgi?id=1617158
